#ism = input("Ismingiz nima?")
#print("Assalomu aleykum" + ism)
#ism = input("Ismingiz nima?\n>>>")
#print("Assalomu aleykum " +ism) 
#yosh = input("Yoshingiz nechchida? \n>>>")
#print(yosh + "yosh bu eng go'zal davrlardan biri.")
#qiziqish = input("Qaysi kasbni tanlamoqchisiz? \n>>>")
#print(qiziqish + "da imkoniyatlar juda ko'p")
#tajriba = input("Ular qanaqa muvaffaqiyatlarga erishgan? \n>>>")
#print(tajriba + "manashu yo'l sizgayam nasib qilsin.")
#xayrlashuv = input("Siz bilan tanishganimdan xursandman" + ism + "\n>>>")
#print("Ko'rishguncha do'stim")
#print("O'n beshning kubi", 15**3, "ga teng")
#print("2*56=", 2*56)
#print("""Men dunyo bozoridagi eng mashhur brendlardan
#biri bo'lmish \"mersedes benz\" niyatim bor """)
#print(16%5)
mashina = ("Renj rover")
yol =  ("Avtomagistral")
print(mashina)